#!/bin/bash

echo "🎯 Adding Test Feedback to Firestore..."

# Use Firebase Firestore REST API to add test feedback
FIREBASE_PROJECT="sparktracks-mvp"

echo ""
echo "📝 Creating 5 test feedback items..."
echo ""
echo "To add test feedback, you have 2 options:"
echo ""
echo "OPTION 1: Via Firebase Console (Recommended - 2 minutes)"
echo "=========================================="
echo "1. Go to: https://console.firebase.google.com/project/$FIREBASE_PROJECT/firestore/data/feedback"
echo "2. Click 'Start collection' or 'Add document'"
echo "3. Collection ID: feedback"
echo "4. Add documents with this data:"
echo ""
echo "Document 1:"
echo "  ID: feedback_test_001"
echo "  Fields:"
echo "    userId: test_user_001"
echo "    userName: Test Parent"
echo "    userEmail: testparent@test.com"
echo "    userType: parent"
echo "    title: Love the new task creation feature!"
echo "    description: The quick task creator is so much easier to use!"
echo "    category: feature"
echo "    rating: 5"
echo "    status: pending"
echo "    submittedAt: (use timestamp, set to now)"
echo ""
echo "Document 2:"
echo "  ID: feedback_test_002"
echo "  Fields:"
echo "    userId: test_user_002"
echo "    userName: Test Coach"
echo "    userEmail: testcoach@test.com"
echo "    userType: coach"
echo "    title: Student privacy feature is excellent"
echo "    description: I can only see my own students now. Great!"
echo "    category: feature"
echo "    rating: 5"
echo "    status: pending"
echo "    submittedAt: (use timestamp, set to now)"
echo ""
echo "=========================================="
echo ""
echo "OPTION 2: Via App (Easiest - 1 minute)"
echo "=========================================="
echo "1. Open: https://sparktracks-mvp.web.app/"
echo "2. Login as any user (or register new)"
echo "3. Click feedback icon in dashboard"
echo "4. Fill out and submit feedback"
echo "5. Check admin panel → Feedback tab"
echo "6. ✅ Should appear instantly!"
echo ""
echo "=========================================="
echo ""
echo "Choose Option 2 for fastest testing! 🚀"

